// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tp03.Core.Data;

namespace Tp03.Core.Migrations
{
    [DbContext(typeof(Tp03Context))]
    [Migration("20211107164952_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Tp03.Core.Entities.BillOfLading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Navio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BillsOfLading");
                });

            modelBuilder.Entity("Tp03.Core.Entities.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BillOfLadingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BillOfLandingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tamanho")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillOfLadingId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("Tp03.Core.Entities.Container", b =>
                {
                    b.HasOne("Tp03.Core.Entities.BillOfLading", "BillOfLading")
                        .WithMany("Containers")
                        .HasForeignKey("BillOfLadingId");

                    b.Navigation("BillOfLading");
                });

            modelBuilder.Entity("Tp03.Core.Entities.BillOfLading", b =>
                {
                    b.Navigation("Containers");
                });
#pragma warning restore 612, 618
        }
    }
}
